/**
 * LOTS identity for rendered artefacts — header band, footer, info strip.
 *
 * The palette is the school's own, fixed in LOTS_Study_Pack_AI_Build_Kit.md:
 * forest green #1D5829, gold #B8860B, paper. Not a parameter like eScholr's
 * multi-tenant SchoolBrand — there is one school, so the colours are constants.
 */
import { rgb } from 'pdf-lib';
import {
  A4, Cursor, DocCtx, Fonts, Margins, drawText, sanitizeWinAnsi, truncateToWidth, embedDataUri,
} from './layout';
import { CREST } from '@/lib/crest';

export const FOREST = rgb(0x1d / 255, 0x58 / 255, 0x29 / 255);
export const GOLD = rgb(0xb8 / 255, 0x86 / 255, 0x0b / 255);
const HAIRLINE = rgb(0.85, 0.85, 0.86);
const FOOTER_H = 28;
const HEADER_H = 76;

export const SCHOOL_NAME = 'Lusaka Oaktree School';

export async function drawHeader(ctx: DocCtx, cur: Cursor, docTitle: string): Promise<void> {
  cur.ensure(HEADER_H + 16);

  // Top colour bar.
  cur.page.drawRectangle({ x: 0, y: A4.height - 8, width: A4.width, height: 8, color: FOREST });

  const crest = await embedDataUri(ctx, CREST);
  let textX = Margins.left;
  if (crest) {
    const h = 46, w = crest.w * (h / crest.h);
    cur.page.drawImage(crest.image, { x: Margins.left, y: cur.y - h, width: w, height: h });
    textX = Margins.left + w + 12;
  }
  const maxW = A4.width - Margins.right - textX;

  drawText(cur.page, SCHOOL_NAME, textX, cur.y - 16, { font: ctx.bold, size: Fonts.headingSize, color: FOREST, maxWidth: maxW });
  drawText(cur.page, docTitle.toUpperCase(), textX, cur.y - 34, { font: ctx.bold, size: Fonts.subheadSize, color: GOLD, maxWidth: maxW });

  cur.advance(HEADER_H);
  cur.page.drawLine({
    start: { x: Margins.left, y: cur.y }, end: { x: A4.width - Margins.right, y: cur.y },
    thickness: 0.5, color: HAIRLINE,
  });
  cur.advance(14);
}

/** A labelled-value strip — SUBJECT / CLASS / TEACHER / WEEK, per the §C4 header block. */
export function drawInfoStrip(ctx: DocCtx, cur: Cursor, pairs: Array<[string, string]>): void {
  const stripH = 38, contentW = A4.width - Margins.left - Margins.right;
  cur.ensure(stripH + 6);
  cur.page.drawRectangle({ x: Margins.left, y: cur.y - stripH, width: contentW, height: stripH, color: rgb(0.96, 0.97, 0.94) });
  const colW = contentW / Math.max(1, pairs.length), cellMaxW = colW - 20;
  pairs.forEach(([label, value], i) => {
    const x = Margins.left + i * colW + 10;
    cur.page.drawText(truncateToWidth(ctx.bold, sanitizeWinAnsi(label.toUpperCase()), Fonts.smallSize - 1, cellMaxW),
      { x, y: cur.y - 14, size: Fonts.smallSize - 1, font: ctx.bold, color: FOREST });
    cur.page.drawText(truncateToWidth(ctx.regular, sanitizeWinAnsi(value || '—'), Fonts.bodySize, cellMaxW),
      { x, y: cur.y - 30, size: Fonts.bodySize, font: ctx.regular, color: rgb(0.1, 0.1, 0.15) });
  });
  cur.advance(stripH + 10);
}

/** Footer + page numbers on every page; a slim continuation header on pages 2+. */
export function drawFooterOnAllPages(ctx: DocCtx, docTitle: string): void {
  const pages = ctx.doc.getPages();
  pages.forEach((p, i) => {
    if (i > 0) {
      p.drawRectangle({ x: 0, y: A4.height - 8, width: A4.width, height: 8, color: FOREST });
      p.drawText(truncateToWidth(ctx.bold, sanitizeWinAnsi(`${SCHOOL_NAME}  ·  ${docTitle}`), Fonts.smallSize, A4.width - Margins.left - Margins.right),
        { x: Margins.left, y: A4.height - 26, size: Fonts.smallSize, font: ctx.bold, color: FOREST });
    }
    p.drawLine({ start: { x: Margins.left, y: FOOTER_H }, end: { x: A4.width - Margins.right, y: FOOTER_H }, thickness: 0.5, color: HAIRLINE });
    const label = `Page ${i + 1} of ${pages.length}`;
    const w = ctx.regular.widthOfTextAtSize(label, Fonts.smallSize);
    p.drawText(label, { x: A4.width - Margins.right - w, y: FOOTER_H - 12, size: Fonts.smallSize, font: ctx.regular, color: rgb(0.5, 0.5, 0.55) });
    p.drawText('Generated by LOTS AI', { x: Margins.left, y: FOOTER_H - 12, size: Fonts.smallSize, font: ctx.regular, color: rgb(0.5, 0.5, 0.55) });
  });
}
