/**
 * Regenerate the logo assets from the master image.
 *
 * Run by hand, not by the build:
 *
 *   npm i -D sharp        (already a devDependency)
 *   node scripts/make_logo.mjs
 *
 * The master is assets/lots-ai-source.png at 1254x1254 and 1.2 MB, which cannot
 * be inlined: a Lusaka connection would feel every byte. Everything that draws
 * the logo reads CREST from lib/crest.ts, so this script writing that one file is
 * what updates the rail, the chat avatars, the interactive study pack and all
 * three PDFs at once.
 *
 * The white margin is trimmed first, so the character fills its box rather than
 * floating in it — at 28px in the rail that is the difference between a logo and
 * a speck. It is then padded back to square on white, because both PDF headers
 * scale by height and lay text out after the width that follows from it.
 */
import sharp from 'sharp';
import { mkdir, writeFile } from 'node:fs/promises';

const SOURCE = 'assets/lots-ai-source.png';
const INLINE = 192;   // the size CREST is inlined at
const PUBLIC = 256;   // the file on disk, for a favicon or an og image

/** Trim the flat white surround, then letterbox back to a square on white. */
function square(size) {
  return sharp(SOURCE)
    .trim({ background: '#ffffff', threshold: 12 })
    .resize(size, size, { fit: 'contain', background: '#ffffff' })
    .flatten({ background: '#ffffff' });
}

await mkdir('public', { recursive: true });
await square(PUBLIC).png({ compressionLevel: 9 }).toFile(`public/lots-ai.png`);

// A palette PNG: the source is a flat illustration, so 128 colours is
// indistinguishable at 192px and roughly a third of the bytes.
const inline = await square(INLINE)
  .png({ palette: true, colours: 128, compressionLevel: 9, effort: 10 })
  .toBuffer();

const uri = `data:image/png;base64,${inline.toString('base64')}`;
await writeFile('lib/crest.ts',
  '// The school crest, inlined so a slow connection never renders a broken page.\n'
  + '// Generated by scripts/make_logo.mjs from assets/lots-ai-source.png - do not edit by hand.\n'
  + `export const CREST = '${uri}';\n`, 'utf8');

console.log(`public/lots-ai.png  ${PUBLIC}x${PUBLIC}`);
console.log(`lib/crest.ts        ${INLINE}x${INLINE}, ${(inline.length / 1024).toFixed(1)} KB (${uri.length} chars as a data URI)`);
