/**
 * Turn assets/Sprout on the move.mp4 into the login door's backdrop.
 *
 * Run by hand, not by the build, exactly like scripts/make_logo.mjs:
 *
 *   node scripts/make_sprout.mjs
 *
 * The master is 512x768, 125 frames at 24fps, 2.5 MB. Three things stop it
 * being used as it stands:
 *
 * 1. 2.5 MB is the whole Addendum D7 payload budget spent on one decorative
 *    element, on the connection least able to afford it.
 *
 * 2. It does not loop. Frame 124 is a mid-stride with the book in one hand;
 *    frame 0 is a wider stance holding it in two, slightly larger. Played on
 *    repeat it visibly jumps.
 *
 * 3. Its background is flat #F7F7F7 rather than the page colour, so any layout
 *    that does not cover the viewport shows the video's edges.
 *
 * (1) is the encode. (3) is settled in globals.css, where the door paints
 * itself SPROUT_GROUND and the video sits over it with object-fit:contain -
 * the two backgrounds are then the same colour and there is no edge to see.
 *
 * (2) is IN and OUT below, and they are measured rather than guessed. Every
 * pair of frames at least three seconds apart was compared (32x48 greyscale,
 * RMS); 110 -> 29 scored 10.6 against an adjacent-frame floor of 26.5, so the
 * join is a smaller step than an ordinary frame advance and needs no dissolve.
 * The naive 124 -> 0 join scores 64.1, which is the jump you can see.
 *
 * A crossfade was tried first and rejected: at the midpoint Sprout carries a
 * translucent second arm. A cut at the right frame beats a blend at the wrong
 * one.
 *
 * If the master is ever replaced, re-run the search rather than trusting these
 * two numbers - they belong to this render and nothing else.
 */
import sharp from 'sharp';
import { spawnSync } from 'node:child_process';
import { mkdir, writeFile, stat, rm } from 'node:fs/promises';

const SRC = 'assets/Sprout on the move.mp4';
const IN = 29;            // first frame of the loop
const OUT = 111;          // one past the last, so the loop is IN..OUT-1
const FPS = 24;
const CRF = 32;           // indistinguishable from the master at this size
const POSTER_W = 320;

/**
 * H.264 only, and deliberately. VP9 was measured against it on this clip and
 * lost at every quality setting - 416 KB at CRF 48 against 243 KB for x264 at
 * CRF 32 - because the master carries generator noise that VP9 spends bits on.
 * One file that every browser plays is worth more here than a second format.
 */
function ffmpeg(args, what) {
  const r = spawnSync('ffmpeg', ['-y', '-v', 'error', ...args], { encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`ffmpeg (${what}) failed:\n${r.stderr || r.stdout}`);
}

const kb = async p => ((await stat(p)).size / 1024).toFixed(1) + ' KB';

await mkdir('public', { recursive: true });

ffmpeg([
  '-i', SRC,
  '-vf', `trim=start_frame=${IN}:end_frame=${OUT},setpts=PTS-STARTPTS`,
  '-an',
  '-c:v', 'libx264', '-crf', String(CRF), '-preset', 'veryslow',
  '-profile:v', 'high', '-pix_fmt', 'yuv420p', '-movflags', '+faststart',
  'public/sprout-walk.mp4',
], 'mp4');

// The poster is the loop's own first frame, so nothing shifts at the moment
// the video takes over from the still.
const still = 'public/.sprout-frame.png';
ffmpeg(['-ss', String(IN / FPS), '-i', SRC, '-frames:v', '1', still], 'poster');

const poster = await sharp(still).resize(POSTER_W).webp({ quality: 72, effort: 6 }).toBuffer();
await rm(still);

const uri = `data:image/webp;base64,${poster.toString('base64')}`;
await writeFile('lib/sprout.ts',
  '// Sprout, still, inlined so the door has him before a single byte of video.\n'
  + `// Generated by scripts/make_sprout.mjs from ${SRC} - do not edit by hand.\n`
  + `export const SPROUT_POSTER = '${uri}';\n`
  + '\n'
  + "// The master's own background colour. globals.css paints the door this so the\n"
  + '// video has no visible edge against the page; keep the two in step.\n'
  + "export const SPROUT_GROUND = '#F7F7F7';\n", 'utf8');

const frames = OUT - IN;
console.log(`public/sprout-walk.mp4   512x768, ${frames} frames, `
  + `${(frames / FPS).toFixed(2)}s, ${await kb('public/sprout-walk.mp4')}`);
console.log(`lib/sprout.ts            ${POSTER_W}px poster, ${(poster.length / 1024).toFixed(1)} KB `
  + `(${uri.length} chars as a data URI)`);
