/**
 * Regenerate the inlined artwork from the two masters in assets/.
 *
 * Run by hand, not by the build:
 *
 *   npm i -D sharp        (already a devDependency)
 *   node scripts/make_logo.mjs
 *
 * There are two marks and they are not interchangeable:
 *
 *   lib/mark.ts   the LOTS AI character. It appears only where LOTS AI is
 *                 speaking - the avatar beside a reply, and beside the typing
 *                 bubble. It is the assistant's face, so it belongs in the
 *                 conversation and nowhere else.
 *   lib/crest.ts  the Lusaka Oaktree School crest. Everything the school puts
 *                 its name to: all three PDFs, the study pack's header, the
 *                 rail and the door. A document carries the school's mark, not
 *                 the assistant's.
 *
 * Neither master can be inlined as it stands - the character is 1.2 MB - and a
 * Lusaka connection would feel every byte, so both are resized here and written
 * out as data URIs.
 */
import sharp from 'sharp';
import { mkdir, writeFile } from 'node:fs/promises';

const INLINE = 192;   // the size each mark is inlined at
const PUBLIC = 256;   // the files on disk, for a favicon or an og image

/**
 * Trim the flat white surround, then letterbox back to a square on white.
 *
 * The trim is not cosmetic. Untrimmed, a mark floats in white and at 28px in the
 * rail it reads as a speck. Squaring afterwards keeps the PDF headers simple:
 * both scale by height and lay text out after the width that follows from it.
 */
function square(source, size) {
  return sharp(source)
    .trim({ background: '#ffffff', threshold: 12 })
    .resize(size, size, { fit: 'contain', background: '#ffffff' })
    .flatten({ background: '#ffffff' });
}

/** A palette PNG: both masters are flat artwork, so 128 colours is
 *  indistinguishable at 192px and roughly a third of the bytes. */
async function inline(source) {
  return square(source, INLINE)
    .png({ palette: true, colours: 128, compressionLevel: 9, effort: 10 })
    .toBuffer();
}

async function emit({ source, publicName, module: modulePath, constant, comment }) {
  await square(source, PUBLIC).png({ compressionLevel: 9 }).toFile(`public/${publicName}`);
  const bytes = await inline(source);
  const uri = `data:image/png;base64,${bytes.toString('base64')}`;
  await writeFile(modulePath,
    `// ${comment}\n`
    + `// Generated by scripts/make_logo.mjs from ${source} - do not edit by hand.\n`
    + `export const ${constant} = '${uri}';\n`, 'utf8');
  console.log(`${modulePath.padEnd(16)} ${INLINE}x${INLINE}, ${(bytes.length / 1024).toFixed(1)} KB `
    + `(${uri.length} chars as a data URI)   ->  public/${publicName}`);
}

await mkdir('public', { recursive: true });

await emit({
  source: 'assets/lots-ai-source.png',
  publicName: 'lots-ai.png',
  module: 'lib/mark.ts',
  constant: 'MARK',
  comment: 'The LOTS AI character, inlined so a slow connection never renders a broken page.',
});

await emit({
  source: 'assets/LOTS LOGO.jpg',
  publicName: 'lots-crest.png',
  module: 'lib/crest.ts',
  constant: 'CREST',
  comment: 'The school crest, inlined so a slow connection never renders a broken page.',
});
