-- 0025  The classes the school actually runs
--
-- `klass` held six rows, all CP4, from scripts/seed.mjs - the demo bootstrap. So a
-- teacher signing in had nothing to choose from, the calendar had six classes in it,
-- and every question about who teaches what was answered from a sixth of the school.
--
-- These are the school's own class streams and the subject each one is taught, read
-- from the whole-school KPI coverage tracker, which is the only place they have ever
-- been written down: 25 streams from CP5 to A2, 22 subjects, 203 class-subject groups.
-- A `klass` row is a teaching group - one stream, one subject - which is why CP5A
-- appears once per subject it is taught.
--
-- `year_group` comes from the tracker's own Level column rather than from trimming a
-- letter off the stream: IG1 and IG2 are whole-cohort groups with no stream letter to
-- trim, and A2 and AS name a level that is not a prefix of the stream either.
--
-- EY and CP1 to CP4 are not here. The tracker does not cover them and no other source
-- lists their streams, so those classes are still added by hand in /admin/classes. The
-- six CP4 rows already in the table are left exactly as they are.
--
-- `periods_per_week` is 4 for every row because the tracker does not record it and the
-- column will not take a null. It is what /admin/classes exists to correct; nothing
-- reads it except the planner's own sense of how much a week holds.
--
-- Safe to re-run.

insert into klass (id, name, year_group, subject_id, periods_per_week) values
  ('A2A-BIO', 'A2A Biology', 'A Level', 'BIO', 4),
  ('A2A-CHEM', 'A2A Chemistry', 'A Level', 'CHEM', 4),
  ('A2A-MATH', 'A2A Mathematics', 'A Level', 'MATH', 4),
  ('A2A-PHYS', 'A2A Physics', 'A Level', 'PHYS', 4),
  ('A2B-ENG', 'A2B English', 'A Level', 'ENG', 4),
  ('A2B-ENGLIT', 'A2B English Literature', 'A Level', 'ENGLIT', 4),
  ('A2B-HIST', 'A2B History', 'A Level', 'HIST', 4),
  ('ASA-BIO', 'ASA Biology', 'AS', 'BIO', 4),
  ('ASA-CHEM', 'ASA Chemistry', 'AS', 'CHEM', 4),
  ('ASA-PHYS', 'ASA Physics', 'AS', 'PHYS', 4),
  ('ASB-ACC', 'ASB Accounting', 'AS', 'ACC', 4),
  ('ASB-BUS', 'ASB Business Studies', 'AS', 'BUS', 4),
  ('ASB-ECON', 'ASB Economics', 'AS', 'ECON', 4),
  ('ASB-ENG', 'ASB English', 'AS', 'ENG', 4),
  ('ASB-HIST', 'ASB History', 'AS', 'HIST', 4),
  ('ASB-IT', 'ASB Information Technology', 'AS', 'IT', 4),
  ('ASB-MATH', 'ASB Mathematics', 'AS', 'MATH', 4),
  ('CP5A-ART', 'CP5A Art & Design', 'CP5', 'ART', 4),
  ('CP5A-ENG', 'CP5A English', 'CP5', 'ENG', 4),
  ('CP5A-FR', 'CP5A French', 'CP5', 'FR', 4),
  ('CP5A-GP', 'CP5A Global Perspectives', 'CP5', 'GP', 4),
  ('CP5A-ICT', 'CP5A ICT', 'CP5', 'ICT', 4),
  ('CP5A-MATH', 'CP5A Mathematics', 'CP5', 'MATH', 4),
  ('CP5A-MDD', 'CP5A Music, Dance & Drama', 'CP5', 'MDD', 4),
  ('CP5A-PE', 'CP5A Physical Education', 'CP5', 'PE', 4),
  ('CP5A-READ', 'CP5A Reading', 'CP5', 'READ', 4),
  ('CP5A-SCI', 'CP5A Science', 'CP5', 'SCI', 4),
  ('CP5A-TEN', 'CP5A PE Tennis', 'CP5', 'TEN', 4),
  ('CP5B-ART', 'CP5B Art & Design', 'CP5', 'ART', 4),
  ('CP5B-ENG', 'CP5B English', 'CP5', 'ENG', 4),
  ('CP5B-FR', 'CP5B French', 'CP5', 'FR', 4),
  ('CP5B-GP', 'CP5B Global Perspectives', 'CP5', 'GP', 4),
  ('CP5B-ICT', 'CP5B ICT', 'CP5', 'ICT', 4),
  ('CP5B-MATH', 'CP5B Mathematics', 'CP5', 'MATH', 4),
  ('CP5B-MDD', 'CP5B Music, Dance & Drama', 'CP5', 'MDD', 4),
  ('CP5B-PE', 'CP5B Physical Education', 'CP5', 'PE', 4),
  ('CP5B-READ', 'CP5B Reading', 'CP5', 'READ', 4),
  ('CP5B-SCI', 'CP5B Science', 'CP5', 'SCI', 4),
  ('CP5B-TEN', 'CP5B PE Tennis', 'CP5', 'TEN', 4),
  ('CP5C-ART', 'CP5C Art & Design', 'CP5', 'ART', 4),
  ('CP5C-ENG', 'CP5C English', 'CP5', 'ENG', 4),
  ('CP5C-FR', 'CP5C French', 'CP5', 'FR', 4),
  ('CP5C-GP', 'CP5C Global Perspectives', 'CP5', 'GP', 4),
  ('CP5C-ICT', 'CP5C ICT', 'CP5', 'ICT', 4),
  ('CP5C-MATH', 'CP5C Mathematics', 'CP5', 'MATH', 4),
  ('CP5C-MDD', 'CP5C Music, Dance & Drama', 'CP5', 'MDD', 4),
  ('CP5C-PE', 'CP5C Physical Education', 'CP5', 'PE', 4),
  ('CP5C-READ', 'CP5C Reading', 'CP5', 'READ', 4),
  ('CP5C-SCI', 'CP5C Science', 'CP5', 'SCI', 4),
  ('CP5C-TEN', 'CP5C PE Tennis', 'CP5', 'TEN', 4),
  ('CP6A-ART', 'CP6A Art & Design', 'CP6', 'ART', 4),
  ('CP6A-ENG', 'CP6A English', 'CP6', 'ENG', 4),
  ('CP6A-FR', 'CP6A French', 'CP6', 'FR', 4),
  ('CP6A-GP', 'CP6A Global Perspectives', 'CP6', 'GP', 4),
  ('CP6A-ICT', 'CP6A ICT', 'CP6', 'ICT', 4),
  ('CP6A-MATH', 'CP6A Mathematics', 'CP6', 'MATH', 4),
  ('CP6A-MDD', 'CP6A Music, Dance & Drama', 'CP6', 'MDD', 4),
  ('CP6A-PE', 'CP6A Physical Education', 'CP6', 'PE', 4),
  ('CP6A-READ', 'CP6A Reading', 'CP6', 'READ', 4),
  ('CP6A-SCI', 'CP6A Science', 'CP6', 'SCI', 4),
  ('CP6A-TEN', 'CP6A PE Tennis', 'CP6', 'TEN', 4),
  ('CP6B-ART', 'CP6B Art & Design', 'CP6', 'ART', 4),
  ('CP6B-ENG', 'CP6B English', 'CP6', 'ENG', 4),
  ('CP6B-FR', 'CP6B French', 'CP6', 'FR', 4),
  ('CP6B-GP', 'CP6B Global Perspectives', 'CP6', 'GP', 4),
  ('CP6B-ICT', 'CP6B ICT', 'CP6', 'ICT', 4),
  ('CP6B-MATH', 'CP6B Mathematics', 'CP6', 'MATH', 4),
  ('CP6B-MDD', 'CP6B Music, Dance & Drama', 'CP6', 'MDD', 4),
  ('CP6B-PE', 'CP6B Physical Education', 'CP6', 'PE', 4),
  ('CP6B-READ', 'CP6B Reading', 'CP6', 'READ', 4),
  ('CP6B-SCI', 'CP6B Science', 'CP6', 'SCI', 4),
  ('CP6B-TEN', 'CP6B PE Tennis', 'CP6', 'TEN', 4),
  ('CP6C-ART', 'CP6C Art & Design', 'CP6', 'ART', 4),
  ('CP6C-ENG', 'CP6C English', 'CP6', 'ENG', 4),
  ('CP6C-FR', 'CP6C French', 'CP6', 'FR', 4),
  ('CP6C-GP', 'CP6C Global Perspectives', 'CP6', 'GP', 4),
  ('CP6C-ICT', 'CP6C ICT', 'CP6', 'ICT', 4),
  ('CP6C-MATH', 'CP6C Mathematics', 'CP6', 'MATH', 4),
  ('CP6C-MDD', 'CP6C Music, Dance & Drama', 'CP6', 'MDD', 4),
  ('CP6C-PE', 'CP6C Physical Education', 'CP6', 'PE', 4),
  ('CP6C-READ', 'CP6C Reading', 'CP6', 'READ', 4),
  ('CP6C-SCI', 'CP6C Science', 'CP6', 'SCI', 4),
  ('CP6C-TEN', 'CP6C PE Tennis', 'CP6', 'TEN', 4),
  ('IG1-ICT', 'IG1 ICT', 'IGCSE 1', 'ICT', 4),
  ('IG1-PE', 'IG1 Physical Education', 'IGCSE 1', 'PE', 4),
  ('IG1A-BIO', 'IG1A Biology', 'IGCSE 1', 'BIO', 4),
  ('IG1A-CHEM', 'IG1A Chemistry', 'IGCSE 1', 'CHEM', 4),
  ('IG1A-ENG', 'IG1A English', 'IGCSE 1', 'ENG', 4),
  ('IG1A-ENGLIT', 'IG1A English Literature', 'IGCSE 1', 'ENGLIT', 4),
  ('IG1A-FR', 'IG1A French', 'IGCSE 1', 'FR', 4),
  ('IG1A-MATH', 'IG1A Mathematics', 'IGCSE 1', 'MATH', 4),
  ('IG1A-PHYS', 'IG1A Physics', 'IGCSE 1', 'PHYS', 4),
  ('IG1B-BIO', 'IG1B Biology', 'IGCSE 1', 'BIO', 4),
  ('IG1B-BUS', 'IG1B Business Studies', 'IGCSE 1', 'BUS', 4),
  ('IG1B-CHEM', 'IG1B Chemistry', 'IGCSE 1', 'CHEM', 4),
  ('IG1B-ECON', 'IG1B Economics', 'IGCSE 1', 'ECON', 4),
  ('IG1B-ENG', 'IG1B English', 'IGCSE 1', 'ENG', 4),
  ('IG1B-ENGLIT', 'IG1B English Literature', 'IGCSE 1', 'ENGLIT', 4),
  ('IG1B-FR', 'IG1B French', 'IGCSE 1', 'FR', 4),
  ('IG1B-GEOG', 'IG1B Geography', 'IGCSE 1', 'GEOG', 4),
  ('IG1B-MATH', 'IG1B Mathematics', 'IGCSE 1', 'MATH', 4),
  ('IG1C-BIO', 'IG1C Biology', 'IGCSE 1', 'BIO', 4),
  ('IG1C-BUS', 'IG1C Business Studies', 'IGCSE 1', 'BUS', 4),
  ('IG1C-CHEM', 'IG1C Chemistry', 'IGCSE 1', 'CHEM', 4),
  ('IG1C-ENG', 'IG1C English', 'IGCSE 1', 'ENG', 4),
  ('IG1C-ENGLIT', 'IG1C English Literature', 'IGCSE 1', 'ENGLIT', 4),
  ('IG1C-GEOG', 'IG1C Geography', 'IGCSE 1', 'GEOG', 4),
  ('IG1C-HIST', 'IG1C History', 'IGCSE 1', 'HIST', 4),
  ('IG1C-MATH', 'IG1C Mathematics', 'IGCSE 1', 'MATH', 4),
  ('IG2-ICT', 'IG2 ICT', 'IGCSE 2', 'ICT', 4),
  ('IG2-PE', 'IG2 Physical Education', 'IGCSE 2', 'PE', 4),
  ('IG2A-BIO', 'IG2A Biology', 'IGCSE 2', 'BIO', 4),
  ('IG2A-CHEM', 'IG2A Chemistry', 'IGCSE 2', 'CHEM', 4),
  ('IG2A-ENG', 'IG2A English', 'IGCSE 2', 'ENG', 4),
  ('IG2A-ENGLIT', 'IG2A English Literature', 'IGCSE 2', 'ENGLIT', 4),
  ('IG2A-FR', 'IG2A French', 'IGCSE 2', 'FR', 4),
  ('IG2A-GEOG', 'IG2A Geography', 'IGCSE 2', 'GEOG', 4),
  ('IG2A-MATH', 'IG2A Mathematics', 'IGCSE 2', 'MATH', 4),
  ('IG2A-PHYS', 'IG2A Physics', 'IGCSE 2', 'PHYS', 4),
  ('IG2B-BIO', 'IG2B Biology', 'IGCSE 2', 'BIO', 4),
  ('IG2B-BUS', 'IG2B Business Studies', 'IGCSE 2', 'BUS', 4),
  ('IG2B-CHEM', 'IG2B Chemistry', 'IGCSE 2', 'CHEM', 4),
  ('IG2B-ENG', 'IG2B English', 'IGCSE 2', 'ENG', 4),
  ('IG2B-GEOG', 'IG2B Geography', 'IGCSE 2', 'GEOG', 4),
  ('IG2B-MATH', 'IG2B Mathematics', 'IGCSE 2', 'MATH', 4),
  ('IG2C-BIO', 'IG2C Biology', 'IGCSE 2', 'BIO', 4),
  ('IG2C-BUS', 'IG2C Business Studies', 'IGCSE 2', 'BUS', 4),
  ('IG2C-CHEM', 'IG2C Chemistry', 'IGCSE 2', 'CHEM', 4),
  ('IG2C-ENG', 'IG2C English', 'IGCSE 2', 'ENG', 4),
  ('IG2C-ENGLIT', 'IG2C English Literature', 'IGCSE 2', 'ENGLIT', 4),
  ('IG2C-GEOG', 'IG2C Geography', 'IGCSE 2', 'GEOG', 4),
  ('IG2C-HIST', 'IG2C History', 'IGCSE 2', 'HIST', 4),
  ('IG2C-MATH', 'IG2C Mathematics', 'IGCSE 2', 'MATH', 4),
  ('LS1A-ART', 'LS1A Art & Design', 'LS1', 'ART', 4),
  ('LS1A-BUS', 'LS1A Business Studies', 'LS1', 'BUS', 4),
  ('LS1A-ENG', 'LS1A English', 'LS1', 'ENG', 4),
  ('LS1A-FR', 'LS1A French', 'LS1', 'FR', 4),
  ('LS1A-GP', 'LS1A Global Perspectives', 'LS1', 'GP', 4),
  ('LS1A-ICT', 'LS1A ICT', 'LS1', 'ICT', 4),
  ('LS1A-MATH', 'LS1A Mathematics', 'LS1', 'MATH', 4),
  ('LS1A-MUS', 'LS1A Music', 'LS1', 'MUS', 4),
  ('LS1A-PE', 'LS1A Physical Education', 'LS1', 'PE', 4),
  ('LS1A-SCI', 'LS1A Science', 'LS1', 'SCI', 4),
  ('LS1B-ART', 'LS1B Art & Design', 'LS1', 'ART', 4),
  ('LS1B-BUS', 'LS1B Business Studies', 'LS1', 'BUS', 4),
  ('LS1B-ENG', 'LS1B English', 'LS1', 'ENG', 4),
  ('LS1B-FR', 'LS1B French', 'LS1', 'FR', 4),
  ('LS1B-GP', 'LS1B Global Perspectives', 'LS1', 'GP', 4),
  ('LS1B-ICT', 'LS1B ICT', 'LS1', 'ICT', 4),
  ('LS1B-MATH', 'LS1B Mathematics', 'LS1', 'MATH', 4),
  ('LS1B-MUS', 'LS1B Music', 'LS1', 'MUS', 4),
  ('LS1B-PE', 'LS1B Physical Education', 'LS1', 'PE', 4),
  ('LS1B-SCI', 'LS1B Science', 'LS1', 'SCI', 4),
  ('LS1C-ART', 'LS1C Art & Design', 'LS1', 'ART', 4),
  ('LS1C-BUS', 'LS1C Business Studies', 'LS1', 'BUS', 4),
  ('LS1C-ENG', 'LS1C English', 'LS1', 'ENG', 4),
  ('LS1C-FR', 'LS1C French', 'LS1', 'FR', 4),
  ('LS1C-GP', 'LS1C Global Perspectives', 'LS1', 'GP', 4),
  ('LS1C-ICT', 'LS1C ICT', 'LS1', 'ICT', 4),
  ('LS1C-MATH', 'LS1C Mathematics', 'LS1', 'MATH', 4),
  ('LS1C-MUS', 'LS1C Music', 'LS1', 'MUS', 4),
  ('LS1C-PE', 'LS1C Physical Education', 'LS1', 'PE', 4),
  ('LS1C-SCI', 'LS1C Science', 'LS1', 'SCI', 4),
  ('LS2A-ART', 'LS2A Art & Design', 'LS2', 'ART', 4),
  ('LS2A-BUS', 'LS2A Business Studies', 'LS2', 'BUS', 4),
  ('LS2A-ENG', 'LS2A English', 'LS2', 'ENG', 4),
  ('LS2A-FR', 'LS2A French', 'LS2', 'FR', 4),
  ('LS2A-GP', 'LS2A Global Perspectives', 'LS2', 'GP', 4),
  ('LS2A-ICT', 'LS2A ICT', 'LS2', 'ICT', 4),
  ('LS2A-MATH', 'LS2A Mathematics', 'LS2', 'MATH', 4),
  ('LS2A-MUS', 'LS2A Music', 'LS2', 'MUS', 4),
  ('LS2A-PE', 'LS2A Physical Education', 'LS2', 'PE', 4),
  ('LS2A-SCI', 'LS2A Science', 'LS2', 'SCI', 4),
  ('LS2B-ART', 'LS2B Art & Design', 'LS2', 'ART', 4),
  ('LS2B-BUS', 'LS2B Business Studies', 'LS2', 'BUS', 4),
  ('LS2B-ENG', 'LS2B English', 'LS2', 'ENG', 4),
  ('LS2B-FR', 'LS2B French', 'LS2', 'FR', 4),
  ('LS2B-GP', 'LS2B Global Perspectives', 'LS2', 'GP', 4),
  ('LS2B-ICT', 'LS2B ICT', 'LS2', 'ICT', 4),
  ('LS2B-MATH', 'LS2B Mathematics', 'LS2', 'MATH', 4),
  ('LS2B-MUS', 'LS2B Music', 'LS2', 'MUS', 4),
  ('LS2B-PE', 'LS2B Physical Education', 'LS2', 'PE', 4),
  ('LS2B-SCI', 'LS2B Science', 'LS2', 'SCI', 4),
  ('LS3A-ART', 'LS3A Art & Design', 'LS3', 'ART', 4),
  ('LS3A-BUS', 'LS3A Business Studies', 'LS3', 'BUS', 4),
  ('LS3A-ENG', 'LS3A English', 'LS3', 'ENG', 4),
  ('LS3A-FR', 'LS3A French', 'LS3', 'FR', 4),
  ('LS3A-GP', 'LS3A Global Perspectives', 'LS3', 'GP', 4),
  ('LS3A-ICT', 'LS3A ICT', 'LS3', 'ICT', 4),
  ('LS3A-MATH', 'LS3A Mathematics', 'LS3', 'MATH', 4),
  ('LS3A-MUS', 'LS3A Music', 'LS3', 'MUS', 4),
  ('LS3A-PE', 'LS3A Physical Education', 'LS3', 'PE', 4),
  ('LS3A-SCI', 'LS3A Science', 'LS3', 'SCI', 4),
  ('LS3B-ART', 'LS3B Art & Design', 'LS3', 'ART', 4),
  ('LS3B-BUS', 'LS3B Business Studies', 'LS3', 'BUS', 4),
  ('LS3B-ENG', 'LS3B English', 'LS3', 'ENG', 4),
  ('LS3B-FR', 'LS3B French', 'LS3', 'FR', 4),
  ('LS3B-GP', 'LS3B Global Perspectives', 'LS3', 'GP', 4),
  ('LS3B-ICT', 'LS3B ICT', 'LS3', 'ICT', 4),
  ('LS3B-MATH', 'LS3B Mathematics', 'LS3', 'MATH', 4),
  ('LS3B-MUS', 'LS3B Music', 'LS3', 'MUS', 4),
  ('LS3B-PE', 'LS3B Physical Education', 'LS3', 'PE', 4),
  ('LS3B-SCI', 'LS3B Science', 'LS3', 'SCI', 4)
on conflict (id) do update
  set name = excluded.name, year_group = excluded.year_group, subject_id = excluded.subject_id;
